version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: upa
    ports:
      - 10022:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  upa_app:
    container_name: upa_app
    links:
      - mongodb
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./env/main.env
    depends_on:
      - mongodb
    command: bash entrypoint.sh

volumes:
  mongodb_data_container: